title: Pozogo
description: ""

author:
  name:    Pozogo
  twitter: ppozogo
  github:  pozogo
  email:   ppozogo@gmail.com

baseurl: ""
url: "http://pozogo.github.io"
gh: "http://github.com/pozogo"

defaultimage: "/assets/images/default.jpg"

permalink: /:categories/:title/

# seo
social:
  name: Pozogo
  links:
    - https://twitter.com/ppozogo
    - https://github.com/pozogo

# Build stuff:
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
sass:
  sass_dir: _sass
  style: compressed

# collections:
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
