title: Pixelchai
description: ""

author:
  name: Pixelchai
  twitter: ppozogo
  github: pixelchai
  email: pixelchai@gmx.com

baseurl: ""
url: "http://pixelchai.github.io"
gh: "http://github.com/pixelchai"

defaultimage: "/assets/images/default.jpg"

permalink: /:categories/:title/

# seo
social:
  name: Pixelchai
  links:
    - https://twitter.com/ppozogo
    - https://github.com/pixelchai

# Build stuff:
markdown: kramdown
  math_engine: katex
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
sass:
  sass_dir: _sass
  style: compressed

# collections:
collections:
  category:
    output: true

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
